+ ./venv/bin/python3 test_myflask.py
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/FlaskProj/test_myflask.py", line 2, in <module>
    from my_flask import app, create_table, create_chat_table
  File "/var/lib/jenkins/workspace/FlaskProj/my_flask.py", line 3, in <module>
    from flask import *
  File "/var/lib/jenkins/workspace/FlaskProj/venv/lib64/python3.9/site-packages/flask/__init__.py", line 7, in <module>
    from .app import Flask as Flask
  File "/var/lib/jenkins/workspace/FlaskProj/venv/lib64/python3.9/site-packages/flask/app.py", line 28, in <module>
    from . import cli
  File "/var/lib/jenkins/workspace/FlaskProj/venv/lib64/python3.9/site-packages/flask/cli.py", line 18, in <module>
    from .helpers import get_debug_flag
  File "/var/lib/jenkins/workspace/FlaskProj/venv/lib64/python3.9/site-packages/flask/helpers.py", line 16, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/lib/jenkins/workspace/FlaskProj/venv/lib64/python3.9/site-packages/werkzeug/urls.py)